version: "2"
services:
  ui-components:
    image: siglusdevops/dev-ui
    ports:
      - "9000:9000"
      - "9876:9876"
    working_dir: /app
    volumes:
      - '.:/app'
    env_file: .env
  image:
    build: .
    image: siglusdevops/ui-components
